export const GET_QUESTIONS='GET_QUESTIONS';
export const GET_SPECIFIC_QUESTION='GET_SPECIFIC_QUESTION';
export const ADD_QUESTION='ADD_QUESTION';
export const DELETE_QUESTION='DELETE_QUESTION';
export const QUESTIONS_LOADING='QUESTIONS_LOADING';

export const GET_ERRORS='GET_ERRORS';
export const SET_CURRENT_USER='SET_CURRENT_USER';
export const GET_PROFILE='GET_PROFILE';
export const PROFILE_LOADING='GET_PROFILE';
export const CLEAR_CURRENT_PROFILE='GET_PROFILE';

export const GET_USER='GET_USER';